window.ARCANA_DECK = {
  "deck": "Arcana",
  "version": "1.0",
  "count": 78,
  "palette": {
    "page": "#F9D9D2",
    "stock": "#FBF3E3",
    "ink": "#35508C",
    "night": "#2E4272",
    "coral": "#E98F8C",
    "gold": "#EDB44E",
    "paleGold": "#F5D7A0",
    "dayField": "#F2B8B4",
    "nightField": "#3A5590",
    "softField": "#F7E3DC",
    "body": "#6A7FAE",
    "meta": "#8D9CC4",
    "eyebrow": "#C98A86"
  },
  "typography": {
    "display": "Cormorant Garamond, serif",
    "ui": "Jost, sans-serif"
  },
  "cardGeometry": {
    "width": 232,
    "height": 396,
    "radius": 12,
    "bleed": 9,
    "goldRule": 1.5,
    "navyRule": 1,
    "topBand": 34,
    "nameBand": 52,
    "windowInset": 8,
    "windowRadius": "96px 96px 6px 6px",
    "restShadow": "0 14px 30px -18px rgba(46,66,114,0.45)",
    "liftShadow": "0 26px 44px -20px rgba(46,66,114,0.5)"
  },
  "emblems": {
    "disc": "132px repeating-conic-gradient(from 0deg,#EDB44E 0 7deg,transparent 7deg 22.5deg) ring + 78px gold core + 48px cream ring",
    "crescent": "104px gold circle, mask radial-gradient(circle at 76% 50%, transparent 50%, #000 51%)",
    "star": "104px 8-point clip-path star (#EDB44E) + 74px rotated 45deg star (#F5D7A0)",
    "rings": "110px 2px gold ring > 78px 1px cream ring > 44px gold disc",
    "pillars": "116x124 gold lintel + two 18px columns + pale gold base",
    "chalice": "92x52 bowl radius 0 0 60px 60px + 12x34 stem + 64x9 foot",
    "blade": "26x150 clip-path blade + pale gold crossguard",
    "eye": "126x74 gold ellipse ring + 42px gold iris + 14px navy pupil",
    "pip": "pipCount shapes, pipSizePx, wrapped in a 130px flex row, gap 14/18",
    "court": "crest = optional crown diamonds / crescent / angled wing bar, arch (crest.arch wide, 116 tall, radius arch/2), centre pip crest.pipSize, plinth crest.plinth x 8"
  },
  "starWash": {
    "night": "radial-gradient(circle at 20% 30%, rgba(251,243,227,0.9) 1px, transparent 1.6px), radial-gradient(circle at 70% 75%, rgba(251,243,227,0.7) 1.2px, transparent 1.8px)",
    "day": "radial-gradient(circle at 25% 35%, rgba(53,80,140,0.22) 1px, transparent 1.6px), radial-gradient(circle at 75% 80%, rgba(237,180,78,0.4) 1.2px, transparent 1.8px)",
    "size": "34px 34px",
    "opacity": 0.5
  },
  "cards": [
    {
      "id": "major-0",
      "index": 0,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Fool",
      "numeral": "0",
      "emblem": "star",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "leap · innocence",
      "upright": "beginnings, faith, spontaneity",
      "reversed": "recklessness, naivety",
      "art": "art/RWS_Tarot_00_Fool.jpg"
    },
    {
      "id": "major-1",
      "index": 1,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Magician",
      "numeral": "I",
      "emblem": "disc",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "will · focus",
      "upright": "manifestation, skill, power",
      "reversed": "manipulation, scattered energy",
      "art": "art/RWS_Tarot_01_Magician.jpg"
    },
    {
      "id": "major-2",
      "index": 2,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The High Priestess",
      "numeral": "II",
      "emblem": "crescent",
      "field": "#3A5590",
      "night": true,
      "keywords": "intuition · secrets",
      "upright": "inner voice, mystery, stillness",
      "reversed": "secrets withheld, ignored instinct",
      "art": "art/RWS_Tarot_02_High_Priestess.jpg"
    },
    {
      "id": "major-3",
      "index": 3,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Empress",
      "numeral": "III",
      "emblem": "rings",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "abundance",
      "upright": "fertility, nurture, plenty",
      "reversed": "stagnation, smothering",
      "art": "art/RWS_Tarot_03_Empress.jpg"
    },
    {
      "id": "major-4",
      "index": 4,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Emperor",
      "numeral": "IV",
      "emblem": "pillars",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "structure",
      "upright": "authority, order, discipline",
      "reversed": "rigidity, domination",
      "art": "art/RWS_Tarot_04_Emperor.jpg"
    },
    {
      "id": "major-5",
      "index": 5,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Hierophant",
      "numeral": "V",
      "emblem": "pillars",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "tradition",
      "upright": "teaching, belief, institutions",
      "reversed": "dogma, rebellion",
      "art": "art/RWS_Tarot_05_Hierophant.jpg"
    },
    {
      "id": "major-6",
      "index": 6,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Lovers",
      "numeral": "VI",
      "emblem": "rings",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "union · choice",
      "upright": "alignment, love, decision",
      "reversed": "discord, misalignment",
      "art": "art/RWS_Tarot_06_Lovers.jpg"
    },
    {
      "id": "major-7",
      "index": 7,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Chariot",
      "numeral": "VII",
      "emblem": "blade",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "drive · control",
      "upright": "momentum, willpower, victory",
      "reversed": "loss of direction",
      "art": "art/RWS_Tarot_07_Chariot.jpg"
    },
    {
      "id": "major-8",
      "index": 8,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "Strength",
      "numeral": "VIII",
      "emblem": "disc",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "courage",
      "upright": "gentle power, patience, resolve",
      "reversed": "self-doubt, force",
      "art": "art/RWS_Tarot_08_Strength.jpg"
    },
    {
      "id": "major-9",
      "index": 9,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Hermit",
      "numeral": "IX",
      "emblem": "star",
      "field": "#3A5590",
      "night": true,
      "keywords": "solitude · light",
      "upright": "retreat, searching, wisdom",
      "reversed": "isolation, avoidance",
      "art": "art/RWS_Tarot_09_Hermit.jpg"
    },
    {
      "id": "major-10",
      "index": 10,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "Wheel of Fortune",
      "numeral": "X",
      "emblem": "rings",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "cycles · fate",
      "upright": "turning point, luck, motion",
      "reversed": "resistance to change",
      "art": "art/RWS_Tarot_10_Wheel_of_Fortune.jpg"
    },
    {
      "id": "major-11",
      "index": 11,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "Justice",
      "numeral": "XI",
      "emblem": "blade",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "balance · truth",
      "upright": "fairness, cause and effect",
      "reversed": "bias, evasion",
      "art": "art/RWS_Tarot_11_Justice.jpg"
    },
    {
      "id": "major-12",
      "index": 12,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Hanged Man",
      "numeral": "XII",
      "emblem": "pillars",
      "field": "#3A5590",
      "night": true,
      "keywords": "surrender",
      "upright": "pause, new perspective",
      "reversed": "stalling, martyrdom",
      "art": "art/RWS_Tarot_12_Hanged_Man.jpg"
    },
    {
      "id": "major-13",
      "index": 13,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "Death",
      "numeral": "XIII",
      "emblem": "crescent",
      "field": "#3A5590",
      "night": true,
      "keywords": "endings · change",
      "upright": "transformation, release",
      "reversed": "clinging, stalled ending",
      "art": "art/RWS_Tarot_13_Death.jpg"
    },
    {
      "id": "major-14",
      "index": 14,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "Temperance",
      "numeral": "XIV",
      "emblem": "chalice",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "measure · flow",
      "upright": "blending, patience, moderation",
      "reversed": "excess, imbalance",
      "art": "art/RWS_Tarot_14_Temperance.jpg"
    },
    {
      "id": "major-15",
      "index": 15,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Devil",
      "numeral": "XV",
      "emblem": "eye",
      "field": "#3A5590",
      "night": true,
      "keywords": "bondage · desire",
      "upright": "attachment, shadow, appetite",
      "reversed": "breaking free",
      "art": "art/RWS_Tarot_15_Devil.jpg"
    },
    {
      "id": "major-16",
      "index": 16,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Tower",
      "numeral": "XVI",
      "emblem": "pillars",
      "field": "#3A5590",
      "night": true,
      "keywords": "rupture",
      "upright": "sudden change, collapse of illusion",
      "reversed": "delayed reckoning",
      "art": "art/RWS_Tarot_16_Tower.jpg"
    },
    {
      "id": "major-17",
      "index": 17,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Star",
      "numeral": "XVII",
      "emblem": "star",
      "field": "#3A5590",
      "night": true,
      "keywords": "hope · healing",
      "upright": "renewal, faith, calm after",
      "reversed": "dimmed hope",
      "art": "art/RWS_Tarot_17_Star.jpg"
    },
    {
      "id": "major-18",
      "index": 18,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Moon",
      "numeral": "XVIII",
      "emblem": "crescent",
      "field": "#3A5590",
      "night": true,
      "keywords": "dream · illusion",
      "upright": "the unconscious, uncertainty",
      "reversed": "clarity returning",
      "art": "art/RWS_Tarot_18_Moon.jpg"
    },
    {
      "id": "major-19",
      "index": 19,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The Sun",
      "numeral": "XIX",
      "emblem": "disc",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "joy · clarity",
      "upright": "vitality, success, warmth",
      "reversed": "dulled confidence",
      "art": "art/RWS_Tarot_19_Sun.jpg"
    },
    {
      "id": "major-20",
      "index": 20,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "Judgement",
      "numeral": "XX",
      "emblem": "eye",
      "field": "#3A5590",
      "night": true,
      "keywords": "reckoning",
      "upright": "awakening, accounting, calling",
      "reversed": "self-doubt, avoidance",
      "art": "art/RWS_Tarot_20_Judgement.jpg"
    },
    {
      "id": "major-21",
      "index": 21,
      "group": "major",
      "suit": "Major Arcana",
      "label": "Major Arcana",
      "name": "The World",
      "numeral": "XXI",
      "emblem": "rings",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "completion",
      "upright": "wholeness, closure, return",
      "reversed": "unfinished business",
      "art": "art/RWS_Tarot_21_World.jpg"
    },
    {
      "id": "wands-1",
      "index": 22,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Ace of Wands",
      "name": "Ace",
      "rank": 1,
      "emblem": "pip",
      "pipCount": 1,
      "pipSizePx": 46,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "spark",
      "art": "art/Wands01.jpg"
    },
    {
      "id": "wands-2",
      "index": 23,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Two of Wands",
      "name": "Two",
      "rank": 2,
      "emblem": "pip",
      "pipCount": 2,
      "pipSizePx": 46,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "venture",
      "art": "art/Wands02.jpg"
    },
    {
      "id": "wands-3",
      "index": 24,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Three of Wands",
      "name": "Three",
      "rank": 3,
      "emblem": "pip",
      "pipCount": 3,
      "pipSizePx": 34,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "growth",
      "art": "art/Wands03.jpg"
    },
    {
      "id": "wands-4",
      "index": 25,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Four of Wands",
      "name": "Four",
      "rank": 4,
      "emblem": "pip",
      "pipCount": 4,
      "pipSizePx": 34,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "foundation",
      "art": "art/Wands04.jpg"
    },
    {
      "id": "wands-5",
      "index": 26,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Five of Wands",
      "name": "Five",
      "rank": 5,
      "emblem": "pip",
      "pipCount": 5,
      "pipSizePx": 28,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "conflict",
      "art": "art/Wands05.jpg"
    },
    {
      "id": "wands-6",
      "index": 27,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Six of Wands",
      "name": "Six",
      "rank": 6,
      "emblem": "pip",
      "pipCount": 6,
      "pipSizePx": 28,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "victory",
      "art": "art/Wands06.jpg"
    },
    {
      "id": "wands-7",
      "index": 28,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Seven of Wands",
      "name": "Seven",
      "rank": 7,
      "emblem": "pip",
      "pipCount": 7,
      "pipSizePx": 28,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "defence",
      "art": "art/Wands07.jpg"
    },
    {
      "id": "wands-8",
      "index": 29,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Eight of Wands",
      "name": "Eight",
      "rank": 8,
      "emblem": "pip",
      "pipCount": 8,
      "pipSizePx": 24,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "speed",
      "art": "art/Wands08.jpg"
    },
    {
      "id": "wands-9",
      "index": 30,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Nine of Wands",
      "name": "Nine",
      "rank": 9,
      "emblem": "pip",
      "pipCount": 9,
      "pipSizePx": 24,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "resolve",
      "art": "art/Wands09.jpg"
    },
    {
      "id": "wands-10",
      "index": 31,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Ten of Wands",
      "name": "Ten",
      "rank": 10,
      "emblem": "pip",
      "pipCount": 10,
      "pipSizePx": 24,
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "burden",
      "art": "art/Wands10.jpg"
    },
    {
      "id": "wands-page",
      "index": 32,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Page of Wands",
      "name": "Page",
      "rank": "Page",
      "emblem": "court",
      "crest": {
        "crown": 1,
        "crownSize": 9,
        "crescent": 0,
        "wings": 0,
        "pipSize": 30,
        "arch": 84,
        "plinth": 72,
        "field": "#3A5590"
      },
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#3A5590",
      "night": true,
      "keywords": "message",
      "art": "art/Wands11.jpg"
    },
    {
      "id": "wands-knight",
      "index": 33,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Knight of Wands",
      "name": "Knight",
      "rank": "Knight",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 0,
        "wings": 1,
        "pipSize": 34,
        "arch": 92,
        "plinth": 96,
        "field": "#2E4272"
      },
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#2E4272",
      "night": true,
      "keywords": "pursuit",
      "art": "art/Wands12.jpg"
    },
    {
      "id": "wands-queen",
      "index": 34,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "Queen of Wands",
      "name": "Queen",
      "rank": "Queen",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 1,
        "wings": 0,
        "pipSize": 38,
        "arch": 100,
        "plinth": 108,
        "field": "#F2B8B4"
      },
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "nurture",
      "art": "art/Wands13.jpg"
    },
    {
      "id": "wands-king",
      "index": 35,
      "group": "wands",
      "suit": "Wands",
      "element": "Fire",
      "label": "King of Wands",
      "name": "King",
      "rank": "King",
      "emblem": "court",
      "crest": {
        "crown": 3,
        "crownSize": 14,
        "crescent": 0,
        "wings": 0,
        "pipSize": 44,
        "arch": 108,
        "plinth": 126,
        "field": "#3A5590"
      },
      "pipFill": "linear-gradient(#EDB44E 0 30%, #35508C 30% 100%)",
      "pipLine": "#35508C",
      "pipRadius": "2px",
      "pipClip": "polygon(32% 0, 68% 0, 68% 100%, 32% 100%)",
      "field": "#3A5590",
      "night": true,
      "keywords": "command",
      "art": "art/Wands14.jpg"
    },
    {
      "id": "cups-1",
      "index": 36,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Ace of Cups",
      "name": "Ace",
      "rank": 1,
      "emblem": "pip",
      "pipCount": 1,
      "pipSizePx": 46,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "new love",
      "art": "art/Cups01.jpg"
    },
    {
      "id": "cups-2",
      "index": 37,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Two of Cups",
      "name": "Two",
      "rank": 2,
      "emblem": "pip",
      "pipCount": 2,
      "pipSizePx": 46,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "partnership",
      "art": "art/Cups02.jpg"
    },
    {
      "id": "cups-3",
      "index": 38,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Three of Cups",
      "name": "Three",
      "rank": 3,
      "emblem": "pip",
      "pipCount": 3,
      "pipSizePx": 34,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "celebration",
      "art": "art/Cups03.jpg"
    },
    {
      "id": "cups-4",
      "index": 39,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Four of Cups",
      "name": "Four",
      "rank": 4,
      "emblem": "pip",
      "pipCount": 4,
      "pipSizePx": 34,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "apathy",
      "art": "art/Cups04.jpg"
    },
    {
      "id": "cups-5",
      "index": 40,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Five of Cups",
      "name": "Five",
      "rank": 5,
      "emblem": "pip",
      "pipCount": 5,
      "pipSizePx": 28,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "loss",
      "art": "art/Cups05.jpg"
    },
    {
      "id": "cups-6",
      "index": 41,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Six of Cups",
      "name": "Six",
      "rank": 6,
      "emblem": "pip",
      "pipCount": 6,
      "pipSizePx": 28,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "memory",
      "art": "art/Cups06.jpg"
    },
    {
      "id": "cups-7",
      "index": 42,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Seven of Cups",
      "name": "Seven",
      "rank": 7,
      "emblem": "pip",
      "pipCount": 7,
      "pipSizePx": 28,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "choices",
      "art": "art/Cups07.jpg"
    },
    {
      "id": "cups-8",
      "index": 43,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Eight of Cups",
      "name": "Eight",
      "rank": 8,
      "emblem": "pip",
      "pipCount": 8,
      "pipSizePx": 24,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "departure",
      "art": "art/Cups08.jpg"
    },
    {
      "id": "cups-9",
      "index": 44,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Nine of Cups",
      "name": "Nine",
      "rank": 9,
      "emblem": "pip",
      "pipCount": 9,
      "pipSizePx": 24,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "wish",
      "art": "art/Cups09.jpg"
    },
    {
      "id": "cups-10",
      "index": 45,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Ten of Cups",
      "name": "Ten",
      "rank": 10,
      "emblem": "pip",
      "pipCount": 10,
      "pipSizePx": 24,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "harmony",
      "art": "art/Cups10.jpg"
    },
    {
      "id": "cups-page",
      "index": 46,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Page of Cups",
      "name": "Page",
      "rank": "Page",
      "emblem": "court",
      "crest": {
        "crown": 1,
        "crownSize": 9,
        "crescent": 0,
        "wings": 0,
        "pipSize": 30,
        "arch": 84,
        "plinth": 72,
        "field": "#3A5590"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#3A5590",
      "night": true,
      "keywords": "message",
      "art": "art/Cups11.jpg"
    },
    {
      "id": "cups-knight",
      "index": 47,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Knight of Cups",
      "name": "Knight",
      "rank": "Knight",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 0,
        "wings": 1,
        "pipSize": 34,
        "arch": 92,
        "plinth": 96,
        "field": "#2E4272"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#2E4272",
      "night": true,
      "keywords": "pursuit",
      "art": "art/Cups12.jpg"
    },
    {
      "id": "cups-queen",
      "index": 48,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "Queen of Cups",
      "name": "Queen",
      "rank": "Queen",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 1,
        "wings": 0,
        "pipSize": 38,
        "arch": 100,
        "plinth": 108,
        "field": "#F2B8B4"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "nurture",
      "art": "art/Cups13.jpg"
    },
    {
      "id": "cups-king",
      "index": 49,
      "group": "cups",
      "suit": "Cups",
      "element": "Water",
      "label": "King of Cups",
      "name": "King",
      "rank": "King",
      "emblem": "court",
      "crest": {
        "crown": 3,
        "crownSize": 14,
        "crescent": 0,
        "wings": 0,
        "pipSize": 44,
        "arch": 108,
        "plinth": 126,
        "field": "#3A5590"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0 0 50% 50%",
      "pipClip": "none",
      "field": "#3A5590",
      "night": true,
      "keywords": "command",
      "art": "art/Cups14.jpg"
    },
    {
      "id": "swords-1",
      "index": 50,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Ace of Swords",
      "name": "Ace",
      "rank": 1,
      "emblem": "pip",
      "pipCount": 1,
      "pipSizePx": 46,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "clarity",
      "art": "art/Swords01.jpg"
    },
    {
      "id": "swords-2",
      "index": 51,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Two of Swords",
      "name": "Two",
      "rank": 2,
      "emblem": "pip",
      "pipCount": 2,
      "pipSizePx": 46,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "stalemate",
      "art": "art/Swords02.jpg"
    },
    {
      "id": "swords-3",
      "index": 52,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Three of Swords",
      "name": "Three",
      "rank": 3,
      "emblem": "pip",
      "pipCount": 3,
      "pipSizePx": 34,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "heartbreak",
      "art": "art/Swords03.jpg"
    },
    {
      "id": "swords-4",
      "index": 53,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Four of Swords",
      "name": "Four",
      "rank": 4,
      "emblem": "pip",
      "pipCount": 4,
      "pipSizePx": 34,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "rest",
      "art": "art/Swords04.jpg"
    },
    {
      "id": "swords-5",
      "index": 54,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Five of Swords",
      "name": "Five",
      "rank": 5,
      "emblem": "pip",
      "pipCount": 5,
      "pipSizePx": 28,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "discord",
      "art": "art/Swords05.jpg"
    },
    {
      "id": "swords-6",
      "index": 55,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Six of Swords",
      "name": "Six",
      "rank": 6,
      "emblem": "pip",
      "pipCount": 6,
      "pipSizePx": 28,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "transit",
      "art": "art/Swords06.jpg"
    },
    {
      "id": "swords-7",
      "index": 56,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Seven of Swords",
      "name": "Seven",
      "rank": 7,
      "emblem": "pip",
      "pipCount": 7,
      "pipSizePx": 28,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "strategy",
      "art": "art/Swords07.jpg"
    },
    {
      "id": "swords-8",
      "index": 57,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Eight of Swords",
      "name": "Eight",
      "rank": 8,
      "emblem": "pip",
      "pipCount": 8,
      "pipSizePx": 24,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "restriction",
      "art": "art/Swords08.jpg"
    },
    {
      "id": "swords-9",
      "index": 58,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Nine of Swords",
      "name": "Nine",
      "rank": 9,
      "emblem": "pip",
      "pipCount": 9,
      "pipSizePx": 24,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "anxiety",
      "art": "art/Swords09.jpg"
    },
    {
      "id": "swords-10",
      "index": 59,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Ten of Swords",
      "name": "Ten",
      "rank": 10,
      "emblem": "pip",
      "pipCount": 10,
      "pipSizePx": 24,
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "ending",
      "art": "art/Swords10.jpg"
    },
    {
      "id": "swords-page",
      "index": 60,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Page of Swords",
      "name": "Page",
      "rank": "Page",
      "emblem": "court",
      "crest": {
        "crown": 1,
        "crownSize": 9,
        "crescent": 0,
        "wings": 0,
        "pipSize": 30,
        "arch": 84,
        "plinth": 72,
        "field": "#3A5590"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#3A5590",
      "night": true,
      "keywords": "message",
      "art": "art/Swords11.jpg"
    },
    {
      "id": "swords-knight",
      "index": 61,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Knight of Swords",
      "name": "Knight",
      "rank": "Knight",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 0,
        "wings": 1,
        "pipSize": 34,
        "arch": 92,
        "plinth": 96,
        "field": "#2E4272"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#2E4272",
      "night": true,
      "keywords": "pursuit",
      "art": "art/Swords12.jpg"
    },
    {
      "id": "swords-queen",
      "index": 62,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "Queen of Swords",
      "name": "Queen",
      "rank": "Queen",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 1,
        "wings": 0,
        "pipSize": 38,
        "arch": 100,
        "plinth": 108,
        "field": "#F2B8B4"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "nurture",
      "art": "art/Swords13.jpg"
    },
    {
      "id": "swords-king",
      "index": 63,
      "group": "swords",
      "suit": "Swords",
      "element": "Air",
      "label": "King of Swords",
      "name": "King",
      "rank": "King",
      "emblem": "court",
      "crest": {
        "crown": 3,
        "crownSize": 14,
        "crescent": 0,
        "wings": 0,
        "pipSize": 44,
        "arch": 108,
        "plinth": 126,
        "field": "#3A5590"
      },
      "pipFill": "#35508C",
      "pipLine": "#35508C",
      "pipRadius": "0",
      "pipClip": "polygon(50% 0, 100% 22%, 50% 100%, 0 22%)",
      "field": "#3A5590",
      "night": true,
      "keywords": "command",
      "art": "art/Swords14.jpg"
    },
    {
      "id": "pentacles-1",
      "index": 64,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Ace of Pentacles",
      "name": "Ace",
      "rank": 1,
      "emblem": "pip",
      "pipCount": 1,
      "pipSizePx": 46,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "seed",
      "art": "art/Pents01.jpg"
    },
    {
      "id": "pentacles-2",
      "index": 65,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Two of Pentacles",
      "name": "Two",
      "rank": 2,
      "emblem": "pip",
      "pipCount": 2,
      "pipSizePx": 46,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "balance",
      "art": "art/Pents02.jpg"
    },
    {
      "id": "pentacles-3",
      "index": 66,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Three of Pentacles",
      "name": "Three",
      "rank": 3,
      "emblem": "pip",
      "pipCount": 3,
      "pipSizePx": 34,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "craft",
      "art": "art/Pents03.jpg"
    },
    {
      "id": "pentacles-4",
      "index": 67,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Four of Pentacles",
      "name": "Four",
      "rank": 4,
      "emblem": "pip",
      "pipCount": 4,
      "pipSizePx": 34,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "holding",
      "art": "art/Pents04.jpg"
    },
    {
      "id": "pentacles-5",
      "index": 68,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Five of Pentacles",
      "name": "Five",
      "rank": 5,
      "emblem": "pip",
      "pipCount": 5,
      "pipSizePx": 28,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "lack",
      "art": "art/Pents05.jpg"
    },
    {
      "id": "pentacles-6",
      "index": 69,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Six of Pentacles",
      "name": "Six",
      "rank": 6,
      "emblem": "pip",
      "pipCount": 6,
      "pipSizePx": 28,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "charity",
      "art": "art/Pents06.jpg"
    },
    {
      "id": "pentacles-7",
      "index": 70,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Seven of Pentacles",
      "name": "Seven",
      "rank": 7,
      "emblem": "pip",
      "pipCount": 7,
      "pipSizePx": 28,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "patience",
      "art": "art/Pents07.jpg"
    },
    {
      "id": "pentacles-8",
      "index": 71,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Eight of Pentacles",
      "name": "Eight",
      "rank": 8,
      "emblem": "pip",
      "pipCount": 8,
      "pipSizePx": 24,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "mastery",
      "art": "art/Pents08.jpg"
    },
    {
      "id": "pentacles-9",
      "index": 72,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Nine of Pentacles",
      "name": "Nine",
      "rank": 9,
      "emblem": "pip",
      "pipCount": 9,
      "pipSizePx": 24,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F7E3DC",
      "night": false,
      "keywords": "comfort",
      "art": "art/Pents09.jpg"
    },
    {
      "id": "pentacles-10",
      "index": 73,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Ten of Pentacles",
      "name": "Ten",
      "rank": 10,
      "emblem": "pip",
      "pipCount": 10,
      "pipSizePx": 24,
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "legacy",
      "art": "art/Pents10.jpg"
    },
    {
      "id": "pentacles-page",
      "index": 74,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Page of Pentacles",
      "name": "Page",
      "rank": "Page",
      "emblem": "court",
      "crest": {
        "crown": 1,
        "crownSize": 9,
        "crescent": 0,
        "wings": 0,
        "pipSize": 30,
        "arch": 84,
        "plinth": 72,
        "field": "#3A5590"
      },
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#3A5590",
      "night": true,
      "keywords": "message",
      "art": "art/Pents11.jpg"
    },
    {
      "id": "pentacles-knight",
      "index": 75,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Knight of Pentacles",
      "name": "Knight",
      "rank": "Knight",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 0,
        "wings": 1,
        "pipSize": 34,
        "arch": 92,
        "plinth": 96,
        "field": "#2E4272"
      },
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#2E4272",
      "night": true,
      "keywords": "pursuit",
      "art": "art/Pents12.jpg"
    },
    {
      "id": "pentacles-queen",
      "index": 76,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "Queen of Pentacles",
      "name": "Queen",
      "rank": "Queen",
      "emblem": "court",
      "crest": {
        "crown": 0,
        "crownSize": 0,
        "crescent": 1,
        "wings": 0,
        "pipSize": 38,
        "arch": 100,
        "plinth": 108,
        "field": "#F2B8B4"
      },
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#F2B8B4",
      "night": false,
      "keywords": "nurture",
      "art": "art/Pents13.jpg"
    },
    {
      "id": "pentacles-king",
      "index": 77,
      "group": "pentacles",
      "suit": "Pentacles",
      "element": "Earth",
      "label": "King of Pentacles",
      "name": "King",
      "rank": "King",
      "emblem": "court",
      "crest": {
        "crown": 3,
        "crownSize": 14,
        "crescent": 0,
        "wings": 0,
        "pipSize": 44,
        "arch": 108,
        "plinth": 126,
        "field": "#3A5590"
      },
      "pipFill": "#EDB44E",
      "pipLine": "#EDB44E",
      "pipRadius": "50%",
      "pipClip": "none",
      "field": "#3A5590",
      "night": true,
      "keywords": "command",
      "art": "art/Pents14.jpg"
    }
  ],
  "artwork": {
    "source": "Pamela Colman Smith, Rider-Waite-Smith tarot (1909) — public domain",
    "host": "Wikimedia Commons Special:FilePath (redirects to upload.wikimedia.org)",
    "naming": {
      "majors": "RWS_Tarot_NN_Name.jpg",
      "minors": "Wands01-14.jpg / Cups01-14.jpg / Swords01-14.jpg / Pents01-14.jpg (11=Page, 12=Knight, 13=Queen, 14=King)"
    },
    "note": "All 78 URLs verified loading. Download once and self-host in /public/cards/<id>.jpg for production; do not hotlink Wikimedia at scale.",
    "treatment": {
      "imgFilter": "saturate(0.88) contrast(1.04) brightness(1.03)",
      "objectFit": "cover",
      "objectPosition": "center 40%",
      "overlay1": "#F2B8B4, mix-blend-mode: multiply, opacity .28",
      "overlay2": "linear-gradient(#EDB44E,#35508C), mix-blend-mode: soft-light, opacity .35",
      "innerEdge": "inset 0 0 0 1px rgba(251,243,227,.35)"
    }
  }
};
